baseURL = 'http://blog.ldatb.com/'
languageCode = 'en-us'
title = "Lucas' Blog"
theme = "risotto"
author = "Lucas de Ataides"
copyright = "© 2023 [Lucas de Ataides](https://ldatb.com)"
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "Lucas' Blog"
description = "My personal blog. Build with [hugo](https://gohugo.io) and [risotto theme](https://github.com/joeroe/risotto)"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/ldatb"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:lucasatab@gmail.com"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
