baseurl      = ""
relativeURLs = "True"
title        = "Lucas de Ataides"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[author]
  name = "Lucas de Ataides"

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "I'm a Software Developer specialized in Cloud Platforms"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # The theme is respecting the prefers-color-scheme of the operating system.
  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "Lucas de Ataides' website"
  keywords = "homepage, blog, developer, cloud, software"
  images = [""]

  [params.logo]
    logoMark     = ">"
    logoText     = "ldatb"
    logoHomeLink = "/"

  [[params.social]]
    name = "email"
    url  = "mailto:ldatb@icloud.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/ldatb"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/lucasdeataides"

  [params.footer]
    trademark = 2023
    rss = false
    copyright = false
    author = false

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Theme provided by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "resume"
    name       = "Résumé"
    url        = "resume/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

[deployment]
  [[deployment.targets]]
    name = "ldatb.com"
    URL = "s3://ldatb.com?region=us-east-1"
    cloudFrontDistributionID = "EWOJZH3V1JA3B"

  [[deployment.matchers]]
    pattern = "^sitemap\\.xml$"
    cacheControl = "public, s-maxage=604800, max-age=86400" #7d,1d
    contentType = "application/xml"

  [[deployment.matchers]]
    pattern = "^.+\\.(css|js)$"
    cacheControl = "public, immutable, max-age=31536000" #1y

  [[deployment.matchers]]
    pattern = "(?i)^.+_hu[0-9a-f]{32}_.+\\.(jpg|jpeg|gif|png|webp)$"
    cacheControl = "public, immutable, max-age=31536000" #1y

  [[deployment.matchers]]
    pattern = "(?i)^.+\\.(jpg|jpeg|gif|png|webp|mp4|woff|woff2)$"
    cacheControl = "public, s-maxage=7776000, max-age=604800" #90d,7d

  [[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json|txt)$"
    cacheControl = "public, s-maxage=604800, max-age=3600" #7d,1h
