name: Upload website files to S3 Bucket

on:
  push:
    branches: ["main"]

jobs:
  upload_to_s3:
    name: Deploy website files to S3 Bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          SOURCE_DIR: 'webpage'
